### ISSUE TITLE
Tripal Curator

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#523]
What will it take to get it to a releasable version?

**Comment by jwest60** [comment]
just gonna post a list of functionality to test here for personal use

### cvterm utilization
- [x] prop tables show 
- [x] cvterms show up
- [x] values for cvterm are correct

### property values
- [x] cvalue search by text value
- [ ] cvalue search by existing cvalue
- [x] cvalue search by no cvalue set

### property curations
- [x] cvterm lookup
- [x] props with cvterm as type display
- [x] props with cvterm as value display

### edit property forms
- [x] edit cvterm type
- [x] edit cvalue type
- [x] split properties

### todo
- linked entity and number of property columns on the property values table when no cvalue is set need to be set or removed
- documentation needs to be written for splitting cvterms, property curations, and likely will need to be updated for property values
- cvalue search by existing cvalue is not working
- theres a dpm that appears after the split form is submitted that should be removed

**Comment by jwest60** [comment]
this module seems to work pretty well, it shouldnt be too difficult to get it into a workable state

as far as i can see, the only things that need to be updated to get this module into a releasable version is the [cvalue search by existing cvalue is not working](https://github.com/statonlab/tripal_curator/issues/19) and the [property values table when no cvalue is set needs to be updated](https://github.com/statonlab/tripal_curator/issues/9)

it could probably use some more documentation as well
